### ISSUE TITLE
Error while running responder

### ISSUE THREAD

**Issue by sohail-sankanur** [aacgood/Cortex-Analyzers#2]
Error while running Reporter responder.

While running the responder this is the error that is popping up. Tried to change multiple things in code but not able to obtain a fix. Any help?

Traceback (most recent call last):  File "/opt/Cortex-Analyzers/responders/Reporter/reporter.py", line 253, in <module>    Reporter().run()  File "/opt/Cortex-Analyzers/responders/Reporter/reporter.py", line 212, in run    caseTaskLogEntries_sorted = sorted(caseTaskLogEntries, key=lambda k: k['createdAt'])  File "/opt/Cortex-Analyzers/responders/Reporter/reporter.py", line 212, in <lambda>    caseTaskLogEntries_sorted = sorted(caseTaskLogEntries, key=lambda k: k['createdAt'])TypeError: string indices must be integers

**Comment by aacgood** [comment]
Hi @sohail-sankanur,

What version of TheHive, TheHive4Py, Cortex and Python are you using?  Does the case you are running the reporter against contain any tasks?

its been a while since ive looked at that code, so ill have to see if I can reproduce it.

**Comment by sohail-sankanur** [comment]
Hi @aacgood,

Thanks for the reply! :)

I am using Thehive4 - Version 4.0.0-1
Python3 - Version Python 3.5.3
Cortex Version 3.0.1-1
Elasticsearch for Cortex. Elasticsearch version 6.8.0
OS - CentOS Linux release 8.2.2004 (Core) 

Cortex and Elasticsearch are running on Docker containers and Thehive is working on the OS.

I have multiple cases in which some of the cases have tasks in them and others do not have any tasks. Tried on all types of cases but it threw the same error. 

Let me know if you would need more info. And thanks for the help!

Looking forward to hearing from you.

Warm Regards,

**Comment by viszsec** [comment]
I spoke to aacgood about this and i had issues as yours. It seems it is not compatible with thehive4 currently.
